site_name: Robinson Handy and Tech Services LLC
site_name_short: RHT Services LLC
site_description: Providing handyman and technology services for the Montgomery, Alabama area.
site_author: Robinson Handy and Technology Services LLC
site_url: https://rhtservices.net
copyright: Robinson Handy and Technology (RHT) Services LLC

# site_favicon: images/lightbulb/favicon.ico

# repository information
repo_url: https://github.com/almostengr/robinsonservices
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8082

# Appearance
theme:
  name: null
  custom_dir: 'theme'
  language: en
  main:
    bgcolor: bg-light
  static_templates:
    - 404.html
    - 500.html
    - contact.php
  # sitemessage
    # - heading: heading
    #   detail: detail
    #   bgcolor: bg-primary
    #   textcolor: text-light
  homemessage:
    - heading: COVID-19 (Coronavirus) Notice
      detail: We take COVID-19 seriously. Masks are worn while performing services indoors, hands are washed before and after each service, and we practice social distancing by performing the service in a room separate from the customer if possible and maintaining 6ft distance.
      bgcolor: bg-primary
      textcolor: text-light
  jumbotron:
    - heading: Get It Done, Without Headaches
      detail: Providing services to homeowners and businesses in Montgomery, AL and surrounding areas.
      url: /services
      background_image: "/images/jumbotron.jpg"
      textcolor: text-warning
      buttoncolor: btn-warning 
  mainnav:
    bgcolor: bg-dark
    linkcolor: text-white
    buttoncolor: btn-warning
    links:
    - url: /about
      name: About
      button: false
    - url: /services
      name: Services
      button: false
    - url: /contact.php
      name: Contact
      button: false
    # - url: https://square.site/book/L1VAAW55MM5GS/robinson-handy-and-technology-services-llc
    - url: /request
      name: Request Services
      button: true
  featurette:
    - heading: Handyman Services
      description: "Our popular handyman services include Ceiling Fan Replacement/Installation, Desk Assembly, Furniture Assembly (Indoor and Outdoor), Lawn Services (Cutting, Edging, Light Landscaping), Lighting Fixture Replacement/Installation, Television (TV) Stand Assembly, and Television (TV) Wall Mounting."
      buttonlink: /services
      buttontext: View Handyman Services
      imageurl: /images/tvmounting.jpg
      bgcolor: bg-light
      textcolor: text-dark
    - heading: Technology Services
      description: "Our popular tech services include Computer Repair, Computer Programming Sessions, Linux Training, Printer Installation/Configuration, and Website Design."
      buttonlink: /services
      buttontext: View Technology Services
      imageurl: /images/thermostat.jpg
      bgcolor: bg-warning
      textcolor: text-dark
    - heading: Service Areas
      description: We primarily provide services in Autauga, Elmore, and Montgomery Counties in Alabama. This includes cities of Millbrook, Montgomery, Prattville, Pike Road, and Wetumpka.
      buttonlink: /about
      buttontext: View Service Areas
      imageurl: /images/service_area.jpg
      bgcolor: bg-light
      textcolor: text-dark
  serviceslist:
    - category:
      name: Handyman Services
      services:
      - title: Air Filter Replacment
      - title: Baby Crib Assembly
      - title: Bed Assembly
      - title: Bookcase Assembly
      - title: Ceiling Fan Replacement / Installation
      - title: Desk Assembly
      - title: Door Knob Replacement
        url: /services/keypadlock
      - title: Doorbell Replacement / Installation
        url: /services/doorbell
      - title: Dresser Assembly
        url: /services/dresser
      - title: Firewood Stand Assembly
      - title: Furniture Assembly
      - title: Hanging Shelves
      - title: Hanging Holiday Lighting and Decorations
      - title: Honey Do Lists
      - title: Kitchen Island Assembly
      - title: Lawn Services (Cutting, Edging, Light Landscaping)
      - title: Lighting Fixture Replacment / Installation
        url: /services/lightfixture
      - title: Outdoor Furniture Assembly
      - title: Patio Furniture Assembly
      - title: Picture Hanging/Hanging Pictures
      - title: Sense Energy Monitor Installation
        url: /services/sensemonitor
        image: /images/sense_install.jpg
      - title: Shed (Small) Assembly
        url: /services/shed1
      - title: Shed (Large) Assembly
        url: /services/shed2
      - title: Shower Head Replacement/Installation
      - title: Smoke Detector Replacement/Installation
      - title: Table Assembly
      - title: Television (TV) Stand Assembly
        url: /services/tvstand
        image: /images/tv_stand_20200926/20200926_080447T.jpg
      - title: Television (TV) Wall Mounting
        url: /services/tvmounting
      - title: Thermostat (Smart and Non-Smart) Replacement / Installation
        url: /services/smartthermostat
      - title: To Do Lists
      - title: Toilet Leak Repair / Valve Replacement
      - title: Trim Repair
      # - title: Washing Machine Hose Replacement
      - title: Window Blind Installation / Replacement
      - title: Window Curtain Installation / Replacement
      - title: Window Drapery Installation / Replacement
    - category:
      name: Technology Services
      services:
      - title: Computer Repair
      - title: Computer Programming Sessions
        url: https://www.youtube.com/watch?v=fg9AgEkuy9o
      - title: Drupal Maintenance and Updates
        url: https://www.youtube.com/watch?v=DjtIx1my2eE
      - title: Google Analytics Installation and Configuration
      - title: Googe Search Console
      - title: Home Networking Solutions
      - title: Linux Training
      - title: Mentoring (Programming and Linux)
      - title: Printer Installation / Configuration
      - title: Robotic Process Automation (RPA) 
      - title: Search Engine Optimization (SEO)
      - title: Selenium WebDriver Automation
      - title: Smart Thermostat Installation
        url: /services/smartthermostat
      - title: Web Application Design
      - title: Website Design
      - title: Wi-Fi Router Installation / Setup
      - title: WordPress Maintenance and Updates
  promotions:
    - heading: "Save 5% on your first service!"
      detail: "Mention that you saw this message on our website and you will get 5% off your first service!"
      buttoncolor: btn-dark-gray
      buttontext: Request Services
      # buttonurl: https://square.site/book/L1VAAW55MM5GS/robinson-handy-and-technology-services-llc
      buttonurl: /request
      bgcolor: bg-warning
      textcolor: text-dark
    # - heading: "Free Business Website"
    #   detail: "During the month of February, one business will be selected each week to have a free business website created. See terms and conditions."
    #   buttontext: Register for Free Website
    #   buttonlink: /freewebsiteoffer
    #   color: bg-light
  subfooter:
    - bgcolor: bg-dark
      textcolor: text-white
      headercolor: text-warning
      columns:
      - heading: About RHTS
        links:
          - url: "tel:(334) 595-9690"
            name: "(334) 595-9690"
            icon: fas fa-phone
          - url: "https://rhtservices.net"
            name: "rhtservices.net"
            icon: fas fa-globe-africa
          - name: "Sun-Fri Hours: By Appointment"
            icon: fas fa-clock
          - name: "Sat Hours: 8 AM (0800) - 8 PM (2000)"
            icon: fas fa-clock
      - heading: Service Areas
        links:
          - name: Montgomery, Alabama
          - name: Pike Road, Alabama            
          - name: Autauga County, Alabama
          - name: Elmore County, Alabama
          - name: Montgomery County, Alabama
      - heading: "Other Links"
        links:
          - name: "Make A Payment"
            url: /payment
            icon: far fa-money-bill-alt
          - name: "Projects"
            url: /projects
            icon: fas fa-tasks
          - name: Uses
            url: /uses
            icon: fas fa-tools
          - name: Frequently Asked Questions (FAQ)
            url: /faq
            icon: fas fa-question
          - name: Privacy Policy
            url: /privacy
            icon: fas fa-user-secret
          - name: Sitemap
            url: /sitemap.xml
            icon: fas fa-sitemap
  footer:
    - bgcolor: bg-black
      textcolor: text-warning
      # links:
      # - url: "tel:(334) 595-9690"
      #   name: "(334) 595-9690"

use_directory_urls: true
strict: false

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra:
  generator: false
