site_name: Robinson Handy and Technology Services LLC
site_description: Providing handyman and technology services for the Montgomery, Alabama area.
site_author: Robinson Handy and Technology Services LLC
site_url: https://rhtservices.net
copyright: Robinson Handy and Technology (RHT) Services LLC


# repository information
repo_url: https://github.com/almostengr/robinsonservices
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8082

# Appearance
theme:
  site_name_short: RHT Services LLC
  site_favicon: /images/logo.ico
  name: null
  custom_dir: 'theme'
  language: en
  main:
    bgcolor: bg-light
  static_templates:
    - 404.html
    - 500.html
    - contact.php
  # sitemessage
    # - heading: heading
    #   detail: detail
    #   bgcolor: bg-primary
    #   textcolor: text-light
  # sitemessage:
  #   - heading: Juneteenth Ceiling Fan Special
  #     detail: Got a ceiling fan that needs to be replaced or upgraded? Now is the time to book your ceiling fan installation appointment for $75! <a href="#">Book now!</a>
  #     bgcolor: bg-success
  #     textcolor: text-light
  # homemessage:
  #   - heading: COVID-19 (Coronavirus) Notice
  #     detail: We take COVID-19 seriously. Masks are worn while performing services indoors, hands are washed before and after each service, and we practice social distancing by performing the service in a room separate from the customer if possible and maintaining 6ft distance.
  #     bgcolor: bg-primary
  #     textcolor: text-light
  jumbotron:
    - heading: Get It Done, Without Headaches
      detail: Providing services to homeowners and businesses in Montgomery, AL and surrounding areas.
      url: /services
      background_image: "/images/jumbotron.jpg"
      textcolor: text-warning
      buttoncolor: btn-warning
  mainnav:
    bgcolor: bg-dark
    linkcolor: text-white
    buttoncolor: btn-warning
    links:
    - url: /services
      name: Services
      button: false
    - url: /specials
      name: Specials
      button: false
    - url: /about
      name: About
      button: false
    - url: /contact.php
      name: Contact
      button: false
    - name: SCHEDULE SERVICE
      url: https://rhtservices.square.site/
      button: true
  featurette:
    - heading: Handyman Services
      description: "Our popular handyman services include Ceiling Fan Replacement and Installation, Furniture Assembly (Indoor and Outdoor), Lighting Fixture Replacement and Installation, Television (TV) Stand Assembly, and Television (TV) Wall Mounting."
      buttonlink: /services
      buttontext: View Handyman Services
      imageurl: /images/tvmounting.jpg
      bgcolor: bg-light
      textcolor: text-dark
    - heading: Technology Services
      description: "Our popular tech services include Computer Repair, Computer Programming Sessions, Linux Training, Printer Installation and Configuration, and Website Design."
      buttonlink: /services
      buttontext: View Technology Services
      imageurl: /images/thermostat_20210213/re20210213_123820.jpg
      bgcolor: bg-warning
      textcolor: text-dark
    - heading: Service Areas
      description: We primarily provide services in Autauga, Elmore, and Montgomery Counties in Alabama. This includes cities of Millbrook, Montgomery, Prattville, Pike Road, and Wetumpka.
      buttonlink: /about
      buttontext: View Service Areas
      imageurl: /images/service_area.jpg
      bgcolor: bg-light
      textcolor: text-dark
  serviceslist:
    - category:
      name: Popular Services
      services:
      ## handyman
      - title: Air Filter Replacement
        url: /services/airfilterreplacement
      - title: Baby Crib Assembly
        image: /images/baby_crib_20200208/re20200208_131750.jpg
      - title: Bed Assembly
        image: /images/headboard_assembly_20200822/re20200822_101231.jpg
      - title: Bookcase Assembly
      - title: Camera Replacement / Installation
      - title: Ceiling Fan Replacement / Installation
        favorite: true
        url: /services/ceilingfan
        image: /images/ceilingfan20210220.jpg
      - title: Desk Assembly
        image: /images/desk_assembly/re20200111_144150.jpg
      - title: Door Knob Replacement
        image: /images/keypad_20201013/re20201013_125226.jpg
        url: /services/keypadlock
      - title: Doorbell Replacement / Installation
        url: /services/doorbell
        image: /images/doorbell_20200919/20200919_160721T.jpg
      - title: Dresser Assembly
        url: /services/dresser
        image: /images/dresser_20200823/20200823_194032T.jpg
      - title: Exterior Door Replacement
      - title: Exercise Equipment Assembly
        image: /images/exercise_20211009/re20210109_113530.jpg
      - title: Furniture Assembly
        url: /services/furniture
        favorite: true
        image: /images/office_chair_20201124/re20201124_110805.jpg
      - title: Grass Cutting
      - title: Kitchen Island Assembly
        image: /images/kitchen_island_20200404/re20200404_102500.jpg
      - title: Lawn Services (Cutting, Edging, Light Landscaping)
        image: /images/landscaping_20200718/re20200719_085301.jpg
      - title: Lighting Fixture Replacement / Installation
        url: /services/lightfixture
        favorite: true
        image: /images/light_fixture_install_20201231/re20201231_155035.jpg
      - title: Mailbox Replacement
      - title: Motion Light Replacement / Installation
        url: https://www.facebook.com/rhtservicesllc/photos/a.107519491418044/107133814789945/
      - title: Patio Furniture Assembly
        image: /images/patio_furniture/re20200527_203222.jpg
      - title: Picture Hanging
        favorite: true
        url: /services/picturehanging
        image: /images/picture_hanging_20210424/re20210424_155249.jpg
      - title: Sense Energy Monitor Installation
        url: /services/sensemonitor
        image: /images/sense_install.jpg
      - title: Shed Assembly
        url: /services/shed2
        image: /images/shed_20200926/20200926_113722T.jpg
      - title: Screen Door Replacement / Installation
      - title: Soundbar Installation
      - title: Storm Door Replacement / Installation
      - title: Table Assembly
      - title: Television (TV) Stand Assembly
        url: /services/tvstand
        favorite: true
        image: /images/tv_stand_20200926/20200926_080447T.jpg
      - title: Television (TV) Wall Mounting
        url: /services/tvmounting
        favorite: true
        image: /images/tvmounting.jpg
      - title: Thermostat (Smart and Non-Smart) Replacement / Installation
        url: /services/smartthermostat
        image: /images/thermostat_20210213/re20210213_123820.jpg
      - title: Toilet Leak Repair / Valve Replacement
      - title: Window Blind Replacement / Installation
      - title: Window Curtain Replacement / Installation
      - title: Window Drapery Replacement / Installation
      ## technology
      - title: Computer Repair
      - title: Computer Programming Sessions
        image: /images/computer_programming.jpg
        favorite: true
        url: https://www.youtube.com/watch?v=fg9AgEkuy9o
      - title: Drupal Maintenance and Updates
        url: https://www.youtube.com/watch?v=DjtIx1my2eE
      - title: Google Analytics Installation and Configuration
      - title: Googe Search Console
      - title: Home Networking Solutions
        favorite: true
        url: /services/homenetwork
        image: /images/home_networking.jpg
      - title: "Linux Training"
        favorite: true
        url: /services/linuxtraining
        image: /images/linux_training.jpg
      - title: Mentoring (Programming and Linux)
      - title: Printer Installation / Configuration
      - title: Robotic Process Automation (RPA)
      - title: Search Engine Optimization (SEO)
      - title: Selenium WebDriver Automation
      - title: Technology Mentoring
      - title: Website Design
      - title: Wi-Fi Router Installation / Setup
      - title: WordPress Maintenance and Updates
  promotions:
    - heading: "Save 5% on your first service!"
      detail: "Mention that you saw this message on our website and you will get 5% off your first service!<br />Not valid for Handy or HomeAdvisor customers."
      buttoncolor: btn-dark-gray
      buttontext: Book Now!
      buttonurl: https://rhtservices.square.site/
      bgcolor: bg-warning
      textcolor: text-dark
    # - heading: "Free Business Website"
    #   detail: "During the month of February, one business will be selected each week to have a free business website created. See terms and conditions."
    #   buttontext: Register for Free Website
    #   buttonlink: /freewebsiteoffer
    #   color: bg-light
  subfooter:
    - bgcolor: bg-dark
      textcolor: text-white
      headercolor: text-warning
      columns:
      - heading: About RHT Services
        links:
          - url: "tel:(334) 595-9690"
            name: "(334) 595-9690"
            icon: bi bi-telephone
          - url: "https://rhtservices.net"
            name: "rhtservices.net"
            icon: bi bi-globe
          - url: https://facebook.com/rhtservicesllc
            name: RHT Services on Facebook
            icon: bi bi-facebook
          - url: /services
            name: Services Offered
            icon: bi bi-kanban
          # - name: "Sat Hours: 8 AM (0800) - 8 PM (2000)<br />Sun-Fri Hours: By Appointment"
          #   icon: bi bi-clock-fill
          - name: "Make A Payment"
            url: /payment
            icon: bi bi-cash
          - name: Book Appointment / Service
            url: https://rhtservices.square.site/
            icon: bi bi-calendar-check
          - name: Customer Reviews
            url: /about#customer-reviews
            icon: bi bi-person-check
          - name: Frequently Asked Questions (FAQ)
            url: /faq
            icon: bi bi-patch-question
          - name: Uses (Recommended Tools)
            url: /uses
            icon: bi bi-tools
          - name: Privacy Policy
            url: /privacy
            icon: bi bi-key
          - name: Sitemap
            url: /sitemap.xml
            icon: bi bi-diagram-3
      - heading: Service Areas
        links:
          - name: Autaugaville
            icon: bi bi-geo-alt-fill
          - name: Cecil
            icon: bi bi-geo-alt-fill
          - name: Coosada
            icon: bi bi-geo-alt-fill
          - name: Deatsville
            icon: bi bi-geo-alt-fill
          - name: Elmore
            icon: bi bi-geo-alt-fill
          - name: Hope Hull
            icon: bi bi-geo-alt-fill
          - name: Millbrook
            icon: bi bi-geo-alt-fill
          - name: Montgomery
            icon: bi bi-geo-alt-fill
          - name: Mount Meigs
            icon: bi bi-geo-alt-fill
          - name: Pike Road
            icon: bi bi-geo-alt-fill
          - name: Pine Level<br />(Autauga and Montgomery Counties)
            icon: bi bi-geo-alt-fill
          - name: Prattville
            icon: bi bi-geo-alt-fill
          - name: Rolling Hills
            icon: bi bi-geo-alt-fill
          - name: Tallassee
            icon: bi bi-geo-alt-fill
          - name: Waugh
            icon: bi bi-geo-alt-fill
          - name: Wetumpka
            icon: bi bi-geo-alt-fill
          - name: Autauga County, Alabama
            icon: bi bi-geo-alt-fill
          - name: Elmore County, Alabama
            icon: bi bi-geo-alt-fill
          - name: Montgomery County, Alabama
            icon: bi bi-geo-alt-fill
      - heading: Popular Services
        links:
          # - name: "Make A Payment"
          #   url: /payment
          #   icon: bi bi-cash
          # - name: Frequently Asked Questions (FAQ)
          #   url: /faq
          #   icon: bi bi-patch-question
          # - name: Privacy Policy
          #   url: /privacy
          #   icon: bi bi-key
          # - name: Sitemap
          #   url: /sitemap.xml
          #   icon: bi bi-diagram-3
          - name: Ceiling Fan Replacement
            icon: bi bi-hammer
            url: /services/ceilingfan
          - name: Furniture Assembly
            icon: bi bi-hammer
            url: /services/furniture
          - name: Home Networking Solutions
            icon: bi bi-hammer
            url: /services/homenetwork
          - name: Lighting Fixture Replacement
            icon: bi bi-hammer
            url: /services/lightfixture
          - name: Linux Training
            icon: bi bi-hammer
            url: /services/linuxtraining
          - name: Picture Hanging
            icon: bi bi-hammer
            url: /services/picturehanging
          - name: TV Stand Assembly
            icon: bi bi-hammer
            url: /services/tvstand
          - name: TV Wall Mounting
            icon: bi bi-hammer
            url: /services/tvmounting
          - name: All Services
            url: /services
            icon: bi bi-list-task
  footer:
    - bgcolor: bg-black
      textcolor: text-warning
      # links:
      # - url: "tel:(334) 595-9690"
      #   name: "(334) 595-9690"

use_directory_urls: true
strict: false

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra:
  generator: false
