name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  updateimages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: find maintwebsite/docs/images/ -iname *png -exec convert {} {}.jpg \;
      name: Converting PNG images to JPG

    - run: find mainwebsite/docs/images/ -iname *png -exec git rm {} \;
      name: Removing PNG images

    - run: find mainwebsite/docs/images/ -iname *jpg -iname *jpeg -exec cp {} mainwebsite/docs/img/ \;
      name: Copying images to img directory

    - run: find mainwebsite/docs/img -iname *jpg -iname *jpeg -exec convert -resize 45% {} {} \;
      name: Convert images to thumbnails

    - name: Run commit on files
      run: bash scripts/ghcommit.sh

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: /usr/bin/python3 -m pip install --upgrade pip

    - run: /usr/bin/python3 -m pip install --upgrade setuptools

    - run: /usr/bin/python3 -m pip install mkdocs==1.1.2

    - run: /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin

    - run: git fetch -p

    - run: /usr/bin/python3 -m mkdocs gh-deploy -f mainwebsite/mkdocs.yml -b website

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Production
      uses: fifsky/ssh-action@master
      with:
        command: cd && cd rhtservices.net && git pull origin website
        host: ${{ secrets.HOSTNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT_NUMBER }}
        user: ${{ secrets.USERNAME }}

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    
    - run: cd rhtservicestest

    - run: dotnet test -c RELEASE rhtservicestest
      
  sitemapping:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Sitemap Ping to search engines
      uses: atymic/sitemap-ping-action@1.0.0
      with:
        sitemap-url: https://rhtservices.net/sitemap.xml
