name: Site Map Ping

on:
  schedule:
    - cron: '15 06 * * 2'

jobs:
  sitemapping:
    runs-on: ubuntu-latest
    steps:
    - name: Sitemap Ping to search engines
      uses: atymic/sitemap-ping-action@1.0.0
      with:
        sitemap-url: https://rhtservices.net/sitemap.xml
